### ISSUE TITLE
[1.14.4] Server can't start with this mod loaded

### ISSUE THREAD

**Issue by systemshaper** [codetaylor/chunkt#2]
Thanks for the mod, I've been searching for a 1.14 chunk loader that includes random ticks, so I was very excited to find this.

When I initially added this mod to my server and placed some of the chunk loaders down in the world, it worked like a charm. However, since then when my server restarts, it gets stuck during startup spamming the message "Netty Epoll Server IO #1/INFO Disconnecting Player (server is still starting): Server is still starting! Please wait before reconnecting." 
The only way to get past this error is to remove the Chunkt mod. I have used other /forceload based chunk loaders on this server without issue. 

I'm running forge 1.14.4 28.2.3, with chunkt-1.14.4-1.0.1

**Comment by codetaylor** [comment]
Thank you for the report. I haven't been able to reproduce this problem during my server tests yet.

Can you please provide a link to the log using a service like hastebin, pastebin, or gist?

Any other information you can provide may help, such as location of the chunk loaders, which dimensions they were in, and other mods you have installed.

**Comment by systemshaper** [comment]
I was afraid this would be hard to nail down.  

- The chunk loaders are all in the overworld (I do have a chunk loader from "plain chunk loaders" in the nether, which have been working without issue for a long time).

- Here are all the mods I'm currently using: https://hastebin.com/ovizofotaf.diff
I can't reproduce this on a single-player world, otherwise I'd try removing other mods to see if there was a specific mod conflict with Chunkt.

- Here's one of the latest logs 
[2020-04-05-1.log](https://github.com/codetaylor/chunkt/files/4434969/2020-04-05-1.log)

Thanks for your help

**Comment by codetaylor** [comment]
Thank you for the info.

Is the `Disconnecting player` message occurring when you try to log in or is the server generating it on its own?

**Comment by codetaylor** [comment]
Also, have you modified the server tick speed at all?

**Comment by codetaylor** [comment]
Can you please test with this build and let me know if the problem persists?

[chunkt-1.14.4-SNAPSHOT.zip](https://github.com/codetaylor/chunkt/files/4435151/chunkt-1.14.4-SNAPSHOT.zip)

**Comment by systemshaper** [comment]
Unfortunately still not able to start up. Server was running (without chunkt installed). Stopped server, added the snapshot above, and started, but server is now back to being stuck in startup and just posting the original error every few minutes. To clarify, the error will happen if I try to connect from a client, but it ALSO happens every few minutes or so without any clients attempting to connect. 

I have not modified the server tick speed, and am not aware of any of the mods I've installed having that effect.

**Comment by systemshaper** [comment]
[latest.log](https://github.com/codetaylor/chunkt/files/4435250/latest.log)
Here is the latest log for the attempted startup with the Snapshot you provided, in case it helps.

**Comment by codetaylor** [comment]
Thank you for your patience and your willingness to help test.

Can you please test this build and, if it fails, provide another log?

[chunkt-1.14.4-SNAPSHOT.zip](https://github.com/codetaylor/chunkt/files/4435395/chunkt-1.14.4-SNAPSHOT.zip)

**Comment by systemshaper** [comment]
Some additional testing I did: 
If I create a new world on my server (with all the mods left the same including chunkt), I can start it up i without issue, go in and place down some chunkt mod loaders, and shut down and restart the server again without issue. But once I point back to my original world folder it won't start (unless I remove chunkt of course). So it's something to do with the actual state of the world it seems. 

I also backed up my server world and tried launching it in single player, and sure enough it hung up at %100 loaded. I removed chunkt and tried again and it loaded. 

EDIT: just saw you already provided a new snapshot to try. I'm in the midst of testing my mods in single player to see if it's a conflict with a particular one (now that I can replicate the general issue in single player) but once I've finished this test I will switch back to my regular setup and test your new snapshot. Thanks

**Comment by codetaylor** [comment]
Thank you. I'm kinda just stabbing in the dark on this one. XD

From what I can tell, something is causing the server to hang before it can complete its initialization. What that is, though, is hard to tell right now.

If you could run the command `/forceload query` on the server world that's having a problem, after it loads without Chunkt, the output might be useful. At this point, I'm just trying to gather as many clues as possible.

The client disconnect message occurring without a client trying to connect seems pretty bizarre to me. That code should never execute unless the server receives a handshake packet from a client.

**Comment by systemshaper** [comment]
Did you take levels in rogue? Cause that stab in the dark was lethal. Server is up with your newest snapshot!
Seriously though, thanks for helping. Hopefully this sticks. Does the solution throw any light onto what the root problem might have been?

**Comment by codetaylor** [comment]
Natural 20!

So, yeah, it does pinpoint the issue. With each world, I keep track of which chunks have chunkloaders in them, then when a world is loaded for the first time, I ensure that the chunks are still force loaded. In the latest snapshot, I simply removed the on-world-load bit because I suspected that it was possibly causing a race condition or some other kind of hang-up.

With that bit removed, chunks should still stay loaded between server restarts due to the way MC handles forceloaded chunks. However, if you manually remove loaded chunks using the `/forceload` command or another mod removes them from MC's forceloaded list, then this snapshot no longer has the ability to ensure they are reloaded after a restart.

You might check that your chunks are still loaded using the `/forceload query` command.

So, tomorrow I need to re-think the way that I'm implementing that feature and solve it with a different strategy.

I won't be able to re-implement it until tomorrow though and I don't want to release it if it's just going to reintroduce the same problems for you. If I gave you a new test build tomorrow, would you have time to test it on your server?

**Comment by systemshaper** [comment]
I'm sure I would

**Comment by ocram9** [comment]
I don't think I have the exact same issue as @systemshaper seems to have but my server also can't start with this mod loaded (it works if I remove the mod). I'm on 1.15.2 and a different forge version (31.1.37) so I don't know if that is the issue here. My server just crashes though, I don't even have the option to join. This also started happening to me after I placed chunk loaders and then restarted.

I know very little about coding/modding so I could be wrong but if I just skim over the crash log it seems to be mixin incompatibility maybe?

Latest log:
https://gist.github.com/ocram9/58979c9acd001c83515589db876e7518

Crash log:
https://gist.github.com/ocram9/2090bdc580613c49e8ad5e182e64f4d0

**Comment by codetaylor** [comment]
@ocram9 Thanks for the report. This is something else entirely and I've moved it to it's own thread here #4

**Comment by codetaylor** [comment]
@systemshaper Thank you again for your help testing.

I have a completed candidate for release, but I would like to make sure that it doesn't re-introduce the server hang that you were experiencing yesterday.

When you have the time, can you please test this build with your world and report back? Thank you!

[chunkt-1.14.4-1.0.2-RC1.zip](https://github.com/codetaylor/chunkt/files/4440289/chunkt-1.14.4-1.0.2-RC1.zip)

**Comment by systemshaper** [comment]
Swapped to the newest build provided above and re-placed chunk loaders. Confirmed chunks were loaded and random ticks are happening when not present. Restarted the server and I did see the old "disconnecting player: server is still starting" error scroll by, but the server did not hang, and successfully started back up. Everything looks great here.

**Comment by codetaylor** [comment]
Great! Thank you!

Please let me know if you experience any new problems.
